In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# reading FACE July data from directory, this is already the CO2 data every 3 hours
July = pd.read_csv('../July.csv', index_col=0)
July = July.iloc[::3]
July.reset_index(inplace=True, drop=True)
July

,station,valid,tmpc,relh,sped,tmpK,index,YEAR,DOY,HOUR,RING,CO2,WIND,WIND_DIR,SOLAR_ANG
0,OQT,2008-07-01 00:53:00,22.78,42.48,3.45,295.93,8395,2008,182,0,0,496.1,1.38,260,-30.77
1,OQT,2008-07-01 03:53:00,16.67,69.51,0.00,289.82,8410,2008,182,3,0,479.6,1.18,220,-18.63
2,OQT,2008-07-01 06:53:00,13.89,83.21,0.00,287.04,8425,2008,182,6,0,488.6,1.13,260,11.32
3,OQT,2008-07-01 09:53:00,12.22,89.95,0.00,285.37,8440,2008,182,9,0,375.6,2.01,240,47.09
4,OQT,2008-07-01 12:53:00,17.78,72.53,0.00,290.93,8455,2008,182,12,0,369.5,1.99,220,76.47
5,OQT,2008-07-01 15:53:00,25.56,37.38,5.75,298.71,8470,2008,182,15,0,365.8,3.32,260,51.45
6,OQT,2008-07-01 18:53:00,27.78,32.84,0.00,300.93,8485,2008,182,18,0,366.1,1.41,320,15.35
7,OQT,2008-07-01 21:53:00,28.89,26.55,5.75,302.04,8500,2008,182,21,0,429.2,0.35,240,-15.69
8,OQT,2008-07-02 00:53:00,25.00,38.74,0.00,298.15,8515,2008,183,0,0,483.6,0.37,0,-30.83
9,OQT,2008-07-02 03:53:00,18.33,70.28,0.00,291.48,8530,2008,183,3,0,525.5,0.29,260,-18.71
10,OQT,2008-07-02 06:53:00,15.56,80.19,0.00,288.71,8545,2008,183,6,0,532.3,0.19,260,11.24
11,OQT,2008-07-02 09:53:00,13.89,86.58,0.00,287.04,8560,2008,183,9,0,409.8,0.64,220,47.04
12,OQT,2008-07-02 12:53:00,18.33,75.51,0.00,291.48,8575,2008,183,12,0,369.4,1.08,340,76.38
13,OQT,2008-07-02 15:53:00,26.11,45.14,0.00,299.26,8590,2008,183,15,0,359.4,0.96,340,51.38
14,OQT,2008-07-02 18:53:00,29.44,28.74,6.90,302.59,8605,2008,183,18,0,365.5,0.70,320,15.35
15,OQT,2008-07-02 21:53:00,30.00,30.09,4.60,303.15,8620,2008,183,21,0,432.5,0.32,120,-15.79
16,OQT,2008-07-03 00:53:00,26.67,42.16,0.00,299.82,8635,2008,184,0,0,488.1,0.48,0,-30.91
17,OQT,2008-07-03 03:53:00,20.56,65.44,0.00,293.71,8650,2008,184,3,0,519.1,0.35,200,-18.75
18,OQT,2008-07-03 06:53:00,17.22,80.93,0.00,290.37,8665,2008,184,6,0,540.4,0.21,220,11.16
19,OQT,2008-07-03 09:53:00,15.56,86.18,0.00,288.71,8680,2008,184,9,0,421.8,0.58,80,46.96
20,OQT,2008-07-03 12:53:00,20.56,67.59,0.00,293.71,8695,2008,184,12,0,374.0,1.14,220,76.31
21,OQT,2008-07-03 15:53:00,27.78,40.84,3.45,300.93,8710,2008,184,15,0,363.3,0.91,240,51.37
22,OQT,2008-07-03 18:53:00,31.11,31.41,9.20,304.26,8725,2008,184,18,0,362.9,0.48,220,15.33
23,OQT,2008-07-03 21:53:00,31.11,30.39,8.05,304.26,8740,2008,184,21,0,442.4,0.30,100,-15.73
24,OQT,2008-07-04 00:53:00,28.89,39.83,0.00,302.04,8755,2008,185,0,0,505.0,0.47,80,-30.99
25,OQT,2008-07-04 03:53:00,23.89,61.66,0.00,297.04,8770,2008,185,3,0,527.9,0.48,300,-18.89
26,OQT,2008-07-04 06:53:00,22.22,68.35,0.00,295.37,8785,2008,185,6,0,548.3,0.33,260,11.09
27,OQT,2008-07-04 09:53:00,21.67,75.57,0.00,294.82,8800,2008,185,9,0,413.9,0.60,340,46.88
28,OQT,2008-07-04 12:53:00,24.44,62.17,3.45,297.59,8815,2008,185,12,0,368.0,1.76,240,76.23
29,OQT,2008-07-04 15:53:00,28.33,52.93,8.05,301.48,8830,2008,185,15,0,362.8,2.02,220,51.34
30,OQT,2008-07-04 18:53:00,31.11,39.17,6.90,304.26,8845,2008,185,18,0,364.3,0.63,220,15.32
31,OQT,2008-07-04 21:53:00,31.67,36.42,4.60,304.82,8860,2008,185,21,0,451.8,0.26,220,-15.81
32,OQT,2008-07-05 00:53:00,21.67,78.49,3.45,294.82,8875,2008,186,0,0,501.0,0.25,140,-31.08
33,OQT,2008-07-05 03:53:00,21.11,87.26,0.00,294.26,8890,2008,186,3,0,540.3,0.16,220,-18.99
34,OQT,2008-07-05 06:53:00,20.56,89.98,0.00,293.71,8905,2008,186,6,0,580.2,0.35,140,11.00
35,OQT,2008-07-05 09:46:00,21.00,88.34,0.00,294.15,8920,2008,186,9,0,407.1,1.90,240,46.79
36,OQT,2008-07-05 12:07:00,21.00,88.34,0.00,294.15,8935,2008,186,12,0,367.0,2.29,260,76.13
37,OQT,2008-07-05 15:02:00,22.00,88.43,8.05,295.15,8950,2008,186,15,0,362.5,2.07,240,51.35
38,OQT,2008-07-05 18:53:00,28.33,54.63,4.60,301.48,8965,2008,186,18,0,368.9,2.53,240,15.31
39,OQT,2008-07-05 21:53:00,28.89,49.22,3.45,302.04,8980,2008,186,21,0,404.7,0.39,40,-15.85
40,OQT,2008-07-06 00:53:00,23.89,73.59,0.00,297.04,8995,2008,187,0,0,465.3,0.23,0,-31.17
41,OQT,2008-07-06 03:53:00,21.11,90.02,0.00,294.26,9010,2008,187,3,0,530.9,0.32,280,-19.08
42,OQT,2008-07-06 06:53:00,21.11,87.26,0.00,294.26,9025,2008,187,6,0,552.0,0.60,120,10.91
43,OQT,2008-07-06 09:53:00,20.56,86.66,0.00,293.71,9040,2008,187,9,0,445.6,1.41,220,46.72
44,OQT,2008-07-06 12:21:00,21.00,88.34,0.00,294.15,9055,2008,187,12,0,381.4,0.92,200,76.03
45,OQT,2008-07-06 15:53:00,26.11,64.54,6.90,299.26,9070,2008,187,15,0,368.2,1.47,260,51.30
46,OQT,2008-07-06 18:53:00,30.56,47.83,6.90,303.71,9085,2008,187,18,0,374.0,0.39,220,15.29
47,OQT,2008-07-06 21:53:00,31.11,40.44,4.60,304.26,9100,2008,187,21,0,471.2,0.50,60,-15.90
48,OQT,2008-07-07 00:53:00,29.44,44.59,0.00,302.59,9115,2008,188,0,0,512.2,0.34,340,-31.27
49,OQT,2008-07-07 03:53:00,23.33,68.57,0.00,296.48,9130,2008,188,3,0,568.6,0.61,60,-19.19
50,OQT,2008-07-07 06:53:00,20.56,80.86,0.00,293.71,9145,2008,188,6,0,605.2,0.38,100,10.82
51,OQT,2008-07-07 09:53:00,18.89,83.79,0.00,292.04,9160,2008,188,9,0,411.6,1.53,260,46.53
52,OQT,2008-07-07 12:53:00,23.33,73.49,5.75,296.48,9175,2008,188,12,0,377.1,1.29,260,75.93
53,OQT,2008-07-07 15:53:00,29.44,54.90,4.60,302.59,9190,2008,188,15,0,371.8,1.81,260,51.20
54,OQT,2008-07-07 18:53:00,31.11,42.02,6.90,304.26,9205,2008,188,18,0,376.1,0.79,240,15.37
55,OQT,2008-07-07 21:53:00,29.44,53.21,0.00,302.59,9220,2008,188,21,0,488.8,0.33,120,-15.96

In [4]:
# Here we add rate constants kf1 and kf2 as well as water fraction to the dataset using functions below
def interpolate(RH_in):
    kf1 = [1.37, 1.48, 1.726, 1.35, 1.78]
    kf2 = [1.71, 12.67,  33.39, 2.06, 14.54]
    T = [298, 299, 298, 308, 308]
    vol = [0.002, 0.01, 0.02, 0.01, 0.02]
    RH_list = []

    for i in range(len(T)):
        P_H2O_sat = np.exp(77.34 - 7235/T[i]-8.2*np.log(T[i]) + 0.005711*T[i])
        P_H2O = 1e5*vol[i]
        RH_list.append(P_H2O/P_H2O_sat*100)

    RH_kf = np.array([RH_list, kf1, kf2]).T
    RH_kf = RH_kf[RH_kf[:, 0].argsort()]

    kf1_hat = np.interp(RH_in, RH_kf[:, 0], RH_kf[:, 1])
    kf2_hat = np.interp(RH_in, RH_kf[:, 0], RH_kf[:, 2])

    return kf1_hat, kf2_hat

def H2O_vol(T_g, RH, P):
    P_H2O_sat = 0.61078*np.exp(17.269*(T_g-273.15)/(T_g-273.15+237.29))*1000
    P_H2O = P_H2O_sat*RH
    vol = P_H2O/P
    return vol

After adding all inputs to the dataset, we are going to import functions that will be used to run gPROMS in Python

In [5]:
import subprocess
import os
import time
import sys
import logging
from threading import Timer
import psutil
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
import pandas as pd


def gPLOT2df(filename):
    """
    Convert .gPLOT file to a pandas dataframe

    Args:
        filename (str) : Name of the gPLOT file.

    Returns:
        df (DataFrame): Pandas dataframe with the time indexes on the rows and the variables on the columns.
    """
    with open(filename, 'r') as f:
        # Read the first line with the number of variables
        nvar = int(f.readline())
        # Read the variablenames
        vars = [f.readline().strip() for i in range(0, nvar)]
        # Read the variablevalues at each time point
        df = pd.read_csv(f, header=None, index_col=False)
        ntime = int((len(df) - 1) / (nvar + 1))
        # Reshape and drop termination element
        df = pd.DataFrame(data=df.values[0:-1].reshape((ntime, nvar + 1)), columns=['Time'] + vars)
    return df

In [7]:
def call_gORUN(gORUN_path, gENCRYPT_name, activity, process, password, working_dir='./', time_out=24*3600,
               verbose=True):
    """
    Calls gORUN and waits for the execution to complete.

    Args:
        gORUN (str): Path to gORUN.bat (must end with gORUN.bat)
        gENCRYPT_name (str): Name of the gENCRYPT file to execute
        activity (str): Activity type  ('sim'|'opt'|'est')
        process (str): Name of the process in the gPROMS file
        password (str): Encryption password of the process in the gPROMS file
        timeout (float): Time out in seconds. After this time the gO:RUN process will be terminated.
        working_dir (str): If the function is not called from the directory containing the input directory,
            use this to change to the right working directory first. The working directory will be set back to the
            original one before terminating.

    Returns:
        result (logical): Returns True for succes, False for error
    """
    # Start timer
    start_time = time.time()

    mpicmd_part_1 = "mpiexec.exe -n 1 -localonly"
    mpicmd_part_2 = "-mpmd"
    mpicmd_part_3 = ": -n NW gCluster.exe"

    # Construct gORUN command
    #gORUN_cmd = [gORUN_path, gENCRYPT_name, activity, process, password]
    gORUN_options =  gENCRYPT_name + " " +  activity + " " +  process + " " +  password
    gORUN_output = ' > ' + activity + '_output.txt'

    np=1
    if np > 1:
        gORUN_path = gORUN_path.rstrip('.bat') + '.exe'
        gORUN_cmd = mpicmd_part_1 + " \"" + gORUN_path + "\" " + mpicmd_part_2 + " " + gORUN_options + " " + \
                    mpicmd_part_3
    else:
        gORUN_cmd = gORUN_path + " " + gORUN_options + gORUN_output
    # Run gO:RUN and log output to file
#    try:
#        with open('./pygORUN.log', 'w') as f:
#     f = open('test.log', 'wb')

    #print(gORUN_cmd)
    print('gPROMS executed')
    process = subprocess.Popen(gORUN_cmd, cwd=working_dir,
                                       encoding='ascii')
#            for line in iter(process.stdout.readline, ""):
#                if verbose:
#                    sys.stdout.write(line)
#                f.write(line.rstrip('\n'))
#                f.flush()
#   except subprocess.CalledProcessError as e:
#        logging.error('Error calling gO:RUN')

    my_timer = Timer(time_out, lambda: kill_process(process))

    try:
        my_timer.start()
        output, error = process.communicate()
    finally:
        my_timer.cancel()

    elapsed_time = time.time() - start_time
    if elapsed_time > time_out:
        print("Activity timed out")


    if process.returncode == 0 and elapsed_time < time_out:
        return True
    else:
        return False

def kill_process(process_to_kill,timestamp="zzz"):
    # ----------------------------------------------------------------------------------------------
    # FEP new solution on killing gORUNs that hang
    try:
        parent = psutil.Process(process_to_kill.pid)
        children = parent.children(recursive=True)
        for child in children:
            child.kill()
        psutil.wait_procs(children, timeout=1)

        # having cleaned up all the children also clean up self
        process_to_kill.terminate()

    except:
        print("Unable to kill")
        pass

In [9]:
# we add one more input, which is the cooling water temperature of adsorption step
h2o_temp = np.zeros(July.shape[0])

for i in range(July.shape[0]):
    if July['tmpK'].iloc[i] <= 278:
        # we dont want the cooling water to be either too cold or too hot
        h2o_temp[i] = 278
    elif July['tmpK'].iloc[i] >= 303:
        h2o_temp[i] = 303
    else:
        h2o_temp[i] = July['tmpK'].iloc[i]

July['h2o_temperature'] = h2o_temp

kf1 = np.zeros(July.shape[0])
kf2 = np.zeros(July.shape[0])

for i in range(July.shape[0]):
    kf1[i], kf2[i] = interpolate([July['relh'].iloc[i]])

July['kf1, bar-1 s-1 (mol/kg)-1'] = kf1
July['kf2, bar2 s-1'] = kf2

# We assume the atmospheric pressure is 96890 Pa using 2008 July data
July['pressure'] = 96890

July['H2O_vol'] = H2O_vol(July['tmpK'], July['relh']*0.01, July['pressure'])
July

,station,valid,tmpc,relh,sped,tmpK,index,YEAR,DOY,HOUR,RING,CO2,WIND,WIND_DIR,SOLAR_ANG,h2o_temperature,"kf1, bar-1 s-1 (mol/kg)-1","kf2, bar2 s-1",pressure,H2O_vol
0,OQT,2008-07-01 00:53:00,22.78,42.48,3.45,295.93,8395,2008,182,0,0,496.1,1.38,260,-30.77,295.93,1.767537,18.890409,96890,0.012154
1,OQT,2008-07-01 03:53:00,16.67,69.51,0.00,289.82,8410,2008,182,3,0,479.6,1.18,220,-18.63,289.82,1.726000,33.390000,96890,0.013613
2,OQT,2008-07-01 06:53:00,13.89,83.21,0.00,287.04,8425,2008,182,6,0,488.6,1.13,260,11.32,287.04,1.726000,33.390000,96890,0.013631
3,OQT,2008-07-01 09:53:00,12.22,89.95,0.00,285.37,8440,2008,182,9,0,375.6,2.01,240,47.09,285.37,1.726000,33.390000,96890,0.013210
4,OQT,2008-07-01 12:53:00,17.78,72.53,0.00,290.93,8455,2008,182,12,0,369.5,1.99,220,76.47,290.93,1.726000,33.390000,96890,0.015237
5,OQT,2008-07-01 15:53:00,25.56,37.38,5.75,298.71,8470,2008,182,15,0,365.8,3.32,260,51.45,298.71,1.777381,15.454184,96890,0.012634
6,OQT,2008-07-01 18:53:00,27.78,32.84,0.00,300.93,8485,2008,182,18,0,366.1,1.41,320,15.35,300.93,1.617310,13.525897,96890,0.012648
7,OQT,2008-07-01 21:53:00,28.89,26.55,5.75,302.04,8500,2008,182,21,0,429.2,0.35,240,-15.69,302.04,1.441419,9.521196,96890,0.010906
8,OQT,2008-07-02 00:53:00,25.00,38.74,0.00,298.15,8515,2008,183,0,0,483.6,0.37,0,-30.83,298.15,1.774756,16.370511,96890,0.012665
9,OQT,2008-07-02 03:53:00,18.33,70.28,0.00,291.48,8530,2008,183,3,0,525.5,0.29,260,-18.71,291.48,1.726000,33.390000,96890,0.015284
10,OQT,2008-07-02 06:53:00,15.56,80.19,0.00,288.71,8545,2008,183,6,0,532.3,0.19,260,11.24,288.71,1.726000,33.390000,96890,0.014630
11,OQT,2008-07-02 09:53:00,13.89,86.58,0.00,287.04,8560,2008,183,9,0,409.8,0.64,220,47.04,287.04,1.726000,33.390000,96890,0.014183
12,OQT,2008-07-02 12:53:00,18.33,75.51,0.00,291.48,8575,2008,183,12,0,369.4,1.08,340,76.38,291.48,1.726000,33.390000,96890,0.016421
13,OQT,2008-07-02 15:53:00,26.11,45.14,0.00,299.26,8590,2008,183,15,0,359.4,0.96,340,51.38,299.26,1.762403,20.682636,96890,0.015762
14,OQT,2008-07-02 18:53:00,29.44,28.74,6.90,302.59,8605,2008,183,18,0,365.5,0.70,320,15.35,302.59,1.464867,11.434903,96890,0.012186
15,OQT,2008-07-02 21:53:00,30.00,30.09,4.60,303.15,8620,2008,183,21,0,432.5,0.32,120,-15.79,303.00,1.479321,12.614586,96890,0.013176
16,OQT,2008-07-03 00:53:00,26.67,42.16,0.00,299.82,8635,2008,184,0,0,488.1,0.48,0,-30.91,299.82,1.768155,18.674803,96890,0.015215
17,OQT,2008-07-03 03:53:00,20.56,65.44,0.00,293.71,8650,2008,184,3,0,519.1,0.35,200,-18.75,293.71,1.726000,33.390000,96890,0.016348
18,OQT,2008-07-03 06:53:00,17.22,80.93,0.00,290.37,8665,2008,184,6,0,540.4,0.21,220,11.16,290.37,1.726000,33.390000,96890,0.016412
19,OQT,2008-07-03 09:53:00,15.56,86.18,0.00,288.71,8680,2008,184,9,0,421.8,0.58,80,46.96,288.71,1.726000,33.390000,96890,0.015723
20,OQT,2008-07-03 12:53:00,20.56,67.59,0.00,293.71,8695,2008,184,12,0,374.0,1.14,220,76.31,293.71,1.726000,33.390000,96890,0.016885
21,OQT,2008-07-03 15:53:00,27.78,40.84,3.45,300.93,8710,2008,184,15,0,363.3,0.91,240,51.37,300.93,1.770703,17.785427,96890,0.015729
22,OQT,2008-07-03 18:53:00,31.11,31.41,9.20,304.26,8725,2008,184,18,0,362.9,0.48,220,15.33,303.00,1.544223,13.070325,96890,0.014655
23,OQT,2008-07-03 21:53:00,31.11,30.39,8.05,304.26,8740,2008,184,21,0,442.4,0.30,100,-15.73,303.00,1.492092,12.745372,96890,0.014179
24,OQT,2008-07-04 00:53:00,28.89,39.83,0.00,302.04,8755,2008,185,0,0,505.0,0.47,80,-30.99,302.04,1.772652,17.104920,96890,0.016361
25,OQT,2008-07-04 03:53:00,23.89,61.66,0.00,297.04,8770,2008,185,3,0,527.9,0.48,300,-18.89,297.04,1.730517,31.813309,96890,0.018863
26,OQT,2008-07-04 06:53:00,22.22,68.35,0.00,295.37,8785,2008,185,6,0,548.3,0.33,260,11.09,295.37,1.726000,33.390000,96890,0.018902
27,OQT,2008-07-04 09:53:00,21.67,75.57,0.00,294.82,8800,2008,185,9,0,413.9,0.60,340,46.88,294.82,1.726000,33.390000,96890,0.020209
28,OQT,2008-07-04 12:53:00,24.44,62.17,3.45,297.59,8815,2008,185,12,0,368.0,1.76,240,76.23,297.59,1.729532,32.156931,96890,0.019657
29,OQT,2008-07-04 15:53:00,28.33,52.93,8.05,301.48,8830,2008,185,15,0,362.8,2.02,220,51.34,301.48,1.747367,25.931301,96890,0.021048
30,OQT,2008-07-04 18:53:00,31.11,39.17,6.90,304.26,8845,2008,185,18,0,364.3,0.63,220,15.32,303.00,1.773926,16.660232,96890,0.018275
31,OQT,2008-07-04 21:53:00,31.67,36.42,4.60,304.82,8860,2008,185,21,0,451.8,0.26,220,-15.81,303.00,1.779234,14.807366,96890,0.017541
32,OQT,2008-07-05 00:53:00,21.67,78.49,3.45,294.82,8875,2008,186,0,0,501.0,0.25,140,-31.08,294.82,1.726000,33.390000,96890,0.020990
33,OQT,2008-07-05 03:53:00,21.11,87.26,0.00,294.26,8890,2008,186,3,0,540.3,0.16,220,-18.99,294.26,1.726000,33.390000,96890,0.022549
34,OQT,2008-07-05 06:53:00,20.56,89.98,0.00,293.71,8905,2008,186,6,0,580.2,0.35,140,11.00,293.71,1.726000,33.390000,96890,0.022478
35,OQT,2008-07-05 09:46:00,21.00,88.34,0.00,294.15,8920,2008,186,9,0,407.1,1.90,240,46.79,294.15,1.726000,33.390000,96890,0.022674
36,OQT,2008-07-05 12:07:00,21.00,88.34,0.00,294.15,8935,2008,186,12,0,367.0,2.29,260,76.13,294.15,1.726000,33.390000,96890,0.022674
37,OQT,2008-07-05 15:02:00,22.00,88.43,8.05,295.15,8950,2008,186,15,0,362.5,2.07,240,51.35,295.15,1.726000,33.390000,96890,0.024129
38,OQT,2008-07-05 18:53:00,28.33,54.63,4.60,301.48,8965,2008,186,18,0,368.9,2.53,240,15.31,301.48,1.744086,27.076709,96890,0.021724
39,OQT,2008-07-05 21:53:00,28.89,49.22,3.45,302.04,8980,2008,186,21,0,404.7,0.39,40,-15.85,302.04,1.754528,23.431616,96890,0.020218
40,OQT,2008-07-06 00:53:00,23.89,73.59,0.00,297.04,8995,2008,187,0,0,465.3,0.23,0,-31.17,297.04,1.726000,33.390000,96890,0.022513
41,OQT,2008-07-06 03:53:00,21.11,90.02,0.00,294.26,9010,2008,187,3,0,530.9,0.32,280,-19.08,294.26,1.726000,33.390000,96890,0.023262
42,OQT,2008-07-06 06:53:00,21.11,87.26,0.00,294.26,9025,2008,187,6,0,552.0,0.60,120,10.91,294.26,1.726000,33.390000,96890,0.022549
43,OQT,2008-07-06 09:53:00,20.56,86.66,0.00,293.71,9040,2008,187,9,0,445.6,1.41,220,46.72,293.71,1.726000,33.390000,96890,0.021649
44,OQT,2008-07-06 12:21:00,21.00,88.34,0.00,294.15,9055,2008,187,12,0,381.4,0.92,200,76.03,294.15,1.726000,33.390000,96890,0.022674
45,OQT,2008-07-06 15:53:00,26.11,64.54,6.90,299.26,9070,2008,187,15,0,368.2,1.47,260,51.30,299.26,1.726000,33.390000,96890,0.022536
46,OQT,2008-07-06 18:53:00,30.56,47.83,6.90,303.71,9085,2008,187,18,0,374.0,0.39,220,15.29,303.00,1.757211,22.495076,96890,0.021627
47,OQT,2008-07-06 21:53:00,31.11,40.44,4.60,304.26,9100,2008,187,21,0,471.2,0.50,60,-15.90,303.00,1.771475,17.515919,96890,0.018868
48,OQT,2008-07-07 00:53:00,29.44,44.59,0.00,302.59,9115,2008,188,0,0,512.2,0.34,340,-31.27,302.59,1.763465,20.312063,96890,0.018907
49,OQT,2008-07-07 03:53:00,23.33,68.57,0.00,296.48,9130,2008,188,3,0,568.6,0.61,60,-19.19,296.48,1.726000,33.390000,96890,0.020282
50,OQT,2008-07-07 06:53:00,20.56,80.86,0.00,293.71,9145,2008,188,6,0,605.2,0.38,100,10.82,293.71,1.726000,33.390000,96890,0.020200
51,OQT,2008-07-07 09:53:00,18.89,83.79,0.00,292.04,9160,2008,188,9,0,411.6,1.53,260,46.53,292.04,1.726000,33.390000,96890,0.018872
52,OQT,2008-07-07 12:53:00,23.33,73.49,5.75,296.48,9175,2008,188,12,0,377.1,1.29,260,75.93,296.48,1.726000,33.390000,96890,0.021737
53,OQT,2008-07-07 15:53:00,29.44,54.90,4.60,302.59,9190,2008,188,15,0,371.8,1.81,260,51.20,302.59,1.743565,27.258626,96890,0.023279
54,OQT,2008-07-07 18:53:00,31.11,42.02,6.90,304.26,9205,2008,188,18,0,376.1,0.79,240,15.37,303.00,1.768425,18.580475,96890,0.019605
55,OQT,2008-07-07 21:53:00,29.44,53.21,0.00,302.59,9220,2008,188,21,0,488.8,0.33,120,-15.96,302.59,1.746827,26.119956,96890,0.022562

Now we have a full dataset ready for gPROMS and optimizations

In [1]:
from PyDDSBB import DDSBB, DDSBBModel

The block below is used to do the DDSBB optimization

In [11]:
t_opt = np.zeros([July.shape[0], 3])

# Type here how many data points you want to optimize in one batch
i_batch = 20
for i in np.arange(i_batch):
    sample = July.iloc[i]

    # Write in the txt file for gRPOMS input
    def write_txt(cycle_time, No_Cycle, Ads0_time, input_file = 'inputs.txt'):
        # input kf1 ,kf2 
        parameter_sens = [sample['kf1, bar-1 s-1 (mol/kg)-1']*1e-5, sample['kf2, bar2 s-1']*1e-10]
        # input all other parameters
        geo_inputs = [sample['H2O_vol'], sample['CO2']*1e-6, sample['tmpK'], sample['pressure'], sample['h2o_temperature']]
        f = open(input_file, "w+")
        f.write("Ads0_time"+"\n")
        f.write(str(np.round(Ads0_time))+"\n"+"\n")     

        f.write("Ads_time"+"\n")
        f.write(str(np.round(cycle_time[0]))+"\n"+"\n")

        f.write("Des_time"+"\n")
        f.write(str(np.round(cycle_time[1]))+"\n"+"\n")

        f.write("No_Cycle"+"\n")
        f.write(str(No_Cycle)+"\n"+"\n")

        f.write("kf_1"+"\n")
        f.write(str(parameter_sens[0])+"\n"+"\n")

        f.write("kf_2"+"\n")
        f.write(str(parameter_sens[1])+"\n"+"\n")

        f.write("y_H2O_0"+"\n")
        f.write(str(geo_inputs[0])+"\n"+"\n")

        f.write("y_CO2_0"+"\n")
        f.write(str(geo_inputs[1])+"\n"+"\n")

        f.write("T_feed"+"\n")
        f.write(str(geo_inputs[2])+"\n"+"\n")

        f.write("P_atm"+"\n")
        f.write(str(geo_inputs[3])+"\n"+"\n")

        f.write("T_h2o"+"\n")
        f.write(str(geo_inputs[4])+"\n"+"\n")

        #print(cycle_time)
        f.close()

    Dict = {}

    # call gPROMS and run
    def sim_output(cycle_time):

        ads = np.round(cycle_time[0])
        Ads0 = ads*2
        vac1 = 5
        vac2 = 200
        vac3 = 100
        des = np.round(cycle_time[1])
        press1 = 20
        press2 = 200
        press3 = 5

        cycle = np.ceil(15000/(cycle_time[0]+cycle_time[1]))

        print(cycle_time, cycle)
        write_txt(cycle_time, No_Cycle = cycle, Ads0_time = Ads0, input_file = 'inputs.txt')
        # make sure this path is correct for your gPROMS directory!!
        gORUN_path = 'C:/Program Files/PSE/gPROMS-core_2021.2.0.55235/bin/goRUN.bat'
        # Type in the name of your .ENCRYPT file
        gENCRYPT_name = 'H2O_export'
        activity = 'sim'
        process = 'H2O_export'
        password = 'H2O_export'

        call_gORUN(gORUN_path, gENCRYPT_name, activity, process, password, working_dir='./', time_out=24*3600,
                    verbose=True)
        # Directory of your gPROMS simulation output
        filename = 'C:/Users/xcai65/OneDrive - Georgia Institute of Technology/study/research/NETL/script/Shubham/optimize_cost/output/H2O_export.gPLOT'
        output_results = gPLOT2df(filename)

        report_Des = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)-ads-press3-press2-press1
        report_Ads = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)
        report_Vac3 = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)-ads-press3-press2-press1-des-vac3

        try:

            prod_mass = output_results['Channel.PROD_MASS'][output_results['Time'] == report_Des].iloc[0] #mol/kg fiber/hr

            Out_CO2_des = output_results['Channel.OUT_CO2_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
            Out_N2_des = output_results['Channel.OUT_N2_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
            Out_H2O_des = output_results['Channel.OUT_H2O_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
            In_CO2_ads = output_results['Channel.IN_CO2_ads'][output_results['Time'] == report_Ads].iloc[0] #mol/channel

            Recovery = Out_CO2_des/In_CO2_ads
            Purity_CO2 = Out_CO2_des/(Out_CO2_des+Out_N2_des)

            E_blower = output_results['Channel.E_blower_ash'][output_results['Time'] == report_Ads].iloc[0]/(Out_CO2_des*44.02*1e-6) # kWh/tCO2
            E_vac = output_results['Channel.E_vac'][output_results['Time'] == report_Des].iloc[0]/(Out_CO2_des*44.02*1e-6) # kWh/tCO2
            Q_sens_ads = -(output_results['Channel.H_ads_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                        output_results['Channel.H_ads_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
            Q_sens_CO2 = (output_results['Channel.H_CO2_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                        output_results['Channel.H_CO2_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
            Q_sens_H2O = (output_results['Channel.H_H2O_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                        output_results['Channel.H_H2O_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2    
            Q_ads_H2O = 50700*Out_H2O_des*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
            Q_ads_CO2 = (output_results['Channel.H_ads_CO2'][output_results['Time'] == report_Vac3].iloc[0]-\
                        output_results['Channel.H_ads_CO2'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2  
            
            E_blower = E_blower*27.78
            E_vac = E_vac*(Out_CO2_des+Out_N2_des)/(Out_CO2_des+Out_N2_des+Out_H2O_des)
            total_cost = (E_blower+E_vac)*0.05+(Q_sens_ads+Q_sens_CO2+Q_ads_CO2+Q_sens_H2O+Q_ads_H2O)*0.015

        except:
            prod_mass = 0
            Recovery = 0
            Out_CO2_des = 0
            Out_N2_des = 0
            Out_H2O_des = 0
            #Purity_H2O = 0
            E_blower = 0
            E_vac = 0
            Q_sens_ads = 0
            Q_sens_CO2 = 0
            Q_sens_H2O = 0
            Q_ads_H2O = 0
            Q_ads_CO2 = 0
            total_cost = 250
        


        print(prod_mass, total_cost)


        return total_cost

    # DDSBB optimization step
    model = DDSBBModel.Problem()
    model.add_objective(sim_output, sense = 'minimize')

    model.add_variable(300., 3600.)
    model.add_variable(300., 3600.)

    model_solver = DDSBB(20, split_method = 'equal_bisection', \
                            variable_selection = 'longest_side', multifidelity = 'nn', \
                            stop_option = {'absolute_tolerance': 0.05, 'relative_tolerance': 0.05, \
                                            'minimum_bound': 0.05, 'sampling_limit': 300, 'time_limit': 10000})


    model_solver.optimize(model)
    t_opt[i, 0] = model_solver.get_optimum()
    t_opt[i, 1:3] = model_solver.get_optimizer()

    print('Optimized cycle time for Month {} is {}'.format(i, t_opt[i, :]))

[300. 300.] 25.0
gPROMS executed
1.201404481364426 115.81915448577216
[3600. 3600.] 3.0
gPROMS executed
0 250
[ 596.29730317 3159.29550999] 4.0
gPROMS executed
0.3448930438062184 90.97101035894735
[3114.35497227  788.03786023] 4.0
gPROMS executed
0.5455027773330583 110.17337303376362
[1320.80870627 1735.83118625] 5.0
gPROMS executed
0.6160904309064269 84.3003338443512
[2258.02755255 2916.46133831] 3.0
gPROMS executed
0.4024632527360302 96.07671060973135
[3259.61378089 2112.02631051] 3.0
gPROMS executed
0.4020046951349224 111.84087290883488
[1909.80564328  740.60069205] 6.0
gPROMS executed
0.7575192288865314 91.59397007790048
[ 408.91416216 1352.35091193] 9.0
gPROMS executed
0.5661683511367939 103.94455376730534
[ 857.95658804 2415.08804078] 5.0
gPROMS executed
0.4878678987120121 84.25766679326657
[1536.30145058 2601.84933947] 4.0
gPROMS executed
0.4723383959311662 86.34081595486987
[1256.83933441  525.96131055] 9.0
gPROMS executed
0.9824481187607742 85.87509891507237
[1232.97503924 3226.44210085] 4.0
gPROMS executed
0.4133992100299023 83.7949889678849
[2980.40967112 1536.63723507] 4.0
gPROMS executed
0.4744640959222942 107.33612800391577
[2781.82364571 3219.66466691] 3.0
gPROMS executed
0.3546758338844068 104.22302341557385
[2369.45240575  394.17212989] 6.0
gPROMS executed
0.6429661148860276 107.56267204229457
[1747.22460333 1288.03086958] 5.0
gPROMS executed
0.6611813466842466 88.79597514801623
[ 938.94143253 1330.36371782] 7.0
gPROMS executed
0.7354369705071384 83.42686946394397
[1752.30971652 2119.91417818] 4.0
gPROMS executed
0.5183033248489416 88.8973935102321
[2846.42651617  383.31242824] 5.0
gPROMS executed
0.5523372994576548 117.58957361380808
[1262.41972212 1272.48286522] 6.0
gPROMS executed
0.7338711269458318 83.84860919310641
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1346.01607624 1274.76612994] 6.0
gPROMS executed
0.7226390240557754 84.45459051799273
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1290.29497485 1119.79953493] 7.0
gPROMS executed
0.7764824798718986 84.02530671148877
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1235.25497537 1159.45083249] 7.0
gPROMS executed
0.7716755403598785 83.67724770191035
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1354.86114058 1178.06031703] 6.0
gPROMS executed
0.7490354042121706 84.52264817699812
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1350.20369593 1347.26246415] 6.0
gPROMS executed
0.7028314432087955 84.49207298532009
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1398.83467043 1311.65119434] 6.0
gPROMS executed
0.7057780912807208 84.90916057105224
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1391.98347876 1544.62887398] 6.0
gPROMS executed
0.6505124460192097 84.86442819561961
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1169.8975692  1229.00865069] 7.0
gPROMS executed
0.7569646685252627 83.35964375349522
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1218.42332377 1458.88819513] 6.0
gPROMS executed
0.6870233389176715 83.61352334005375
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1287.62072935 1205.48601534] 7.0
gPROMS executed
0.7503981110549616 84.016809415859
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1220.57875969 2014.40571595] 5.0
gPROMS executed
0.5685441028427696 83.67833939340147
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1201.35351523 1506.70003399] 6.0
gPROMS executed
0.6761254501706093 83.5278515992464
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1165.16432777 1870.84783853] 5.0
gPROMS executed
0.596746734035054 83.41168548122032
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1223.8498958  1341.69755783] 6.0
gPROMS executed
0.7179937882480708 83.62762544985677
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1157.12625858 2261.2856757 ] 5.0
gPROMS executed
0.5285597980125952 83.41630318937636
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1101.78057133 2449.00422565] 5.0
gPROMS executed
0.5000683629068687 83.28079122370755
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
[1093.3832466  1575.51960319] 6.0
gPROMS executed
0.664107387562121 83.19279083577779
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'
WARNING: Could not locate the 'glpsol' executable, which is required for
solver 'glpk'

RuntimeError: ERROR: Failed to train DDCU

In [25]:
print(t_opt)

[[  83.25051787 1076.79862204 2387.66621783]
 [ 100.2296519  1448.71292553 1346.0682509 ]
 [ 116.20978145 1373.2295116  1804.18191783]
 [ 138.60206982 1681.93603146 2461.06941159]
 [ 114.59246284 1721.27339912 1488.61689627]
 [  95.62265192 1274.4225767  3567.29138734]
 [  97.71267101 1198.28900574 1204.32235546]
 [  90.78085018  991.45225838  906.87645171]
 [  84.08655177 1044.23829831 1544.97118565]
 [  98.89975325 1320.37242339 2487.79642452]
 [ 109.54722496 1369.94445816 1645.24054414]
 [ 129.4526497  1590.23526102 1481.35598828]
 [ 119.40381278 1743.75       1537.5       ]
 [ 101.31255596 1203.45833781 2112.20920222]
 [  99.77422876  962.73113899  992.59091467]
 [  92.89241981  942.70842561 1326.82507268]
 [  87.24552644  994.08373359 1039.24667811]
 [  95.31579565 1324.50896562 2511.92228785]
 [ 110.93902867 1281.19881833 2074.90021548]
 [ 128.73501095 1561.25055783 1575.98767073]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]
 [   0.            0.            0.        ]]

In [26]:
df_out = pd.DataFrame(t_opt, columns=['E_cost', 'Ads_t, s', 'Des_t, s'])

July = July.reset_index(drop=True)
July = pd.concat([July, df_out], axis = 1)
July

,station,valid,tmpc,relh,sped,tmpK,index,YEAR,DOY,HOUR,...,"kf1, bar-1 s-1 (mol/kg)-1","kf2, bar2 s-1",pressure,H2O_vol,E_cost,"Ads_t, s","Des_t, s",E_cost,"Ads_t, s","Des_t, s"
0,OQT,2008-07-01 00:53:00,22.78,42.48,3.45,295.93,8395,2008,182,0,...,1.767537,18.890409,96890,0.012154,64.051434,1417.627221,1491.831213,83.250518,1076.798622,2387.666218
1,OQT,2008-07-01 03:53:00,16.67,69.51,0.00,289.82,8410,2008,182,3,...,1.726000,33.390000,96890,0.013613,79.386534,1988.200884,1981.100348,100.229652,1448.712926,1346.068251
2,OQT,2008-07-01 06:53:00,13.89,83.21,0.00,287.04,8425,2008,182,6,...,1.726000,33.390000,96890,0.013631,93.426403,1852.994753,2196.511280,116.209781,1373.229512,1804.181918
3,OQT,2008-07-01 09:53:00,12.22,89.95,0.00,285.37,8440,2008,182,9,...,1.726000,33.390000,96890,0.013210,112.496731,2222.901529,2165.653455,138.602070,1681.936031,2461.069412
4,OQT,2008-07-01 12:53:00,17.78,72.53,0.00,290.93,8455,2008,182,12,...,1.726000,33.390000,96890,0.015237,91.596659,2362.500000,1950.000000,114.592463,1721.273399,1488.616896
5,OQT,2008-07-01 15:53:00,25.56,37.38,5.75,298.71,8470,2008,182,15,...,1.777381,15.454184,96890,0.012634,73.528730,1506.692712,1460.430979,95.622652,1274.422577,3567.291387
6,OQT,2008-07-01 18:53:00,27.78,32.84,0.00,300.93,8485,2008,182,18,...,1.617310,13.525897,96890,0.012648,74.743761,1433.704797,1371.310072,97.712671,1198.289006,1204.322355
7,OQT,2008-07-01 21:53:00,28.89,26.55,5.75,302.04,8500,2008,182,21,...,1.441419,9.521196,96890,0.010906,68.433496,1162.000733,1176.408103,90.780850,991.452258,906.876452
8,OQT,2008-07-02 00:53:00,25.00,38.74,0.00,298.15,8515,2008,183,0,...,1.774756,16.370511,96890,0.012665,64.666658,1389.233331,1818.726070,84.086552,1044.238298,1544.971186
9,OQT,2008-07-02 03:53:00,18.33,70.28,0.00,291.48,8530,2008,183,3,...,1.726000,33.390000,96890,0.015284,78.409278,1829.748308,1808.089060,98.899753,1320.372423,2487.796425
10,OQT,2008-07-02 06:53:00,15.56,80.19,0.00,288.71,8545,2008,183,6,...,1.726000,33.390000,96890,0.014630,0.000000,0.000000,0.000000,109.547225,1369.944458,1645.240544
11,OQT,2008-07-02 09:53:00,13.89,86.58,0.00,287.04,8560,2008,183,9,...,1.726000,33.390000,96890,0.014183,0.000000,0.000000,0.000000,129.452650,1590.235261,1481.355988
12,OQT,2008-07-02 12:53:00,18.33,75.51,0.00,291.48,8575,2008,183,12,...,1.726000,33.390000,96890,0.016421,0.000000,0.000000,0.000000,119.403813,1743.750000,1537.500000
13,OQT,2008-07-02 15:53:00,26.11,45.14,0.00,299.26,8590,2008,183,15,...,1.762403,20.682636,96890,0.015762,0.000000,0.000000,0.000000,101.312556,1203.458338,2112.209202
14,OQT,2008-07-02 18:53:00,29.44,28.74,6.90,302.59,8605,2008,183,18,...,1.464867,11.434903,96890,0.012186,0.000000,0.000000,0.000000,99.774229,962.731139,992.590915
15,OQT,2008-07-02 21:53:00,30.00,30.09,4.60,303.15,8620,2008,183,21,...,1.479321,12.614586,96890,0.013176,0.000000,0.000000,0.000000,92.892420,942.708426,1326.825073
16,OQT,2008-07-03 00:53:00,26.67,42.16,0.00,299.82,8635,2008,184,0,...,1.768155,18.674803,96890,0.015215,0.000000,0.000000,0.000000,87.245526,994.083734,1039.246678
17,OQT,2008-07-03 03:53:00,20.56,65.44,0.00,293.71,8650,2008,184,3,...,1.726000,33.390000,96890,0.016348,0.000000,0.000000,0.000000,95.315796,1324.508966,2511.922288
18,OQT,2008-07-03 06:53:00,17.22,80.93,0.00,290.37,8665,2008,184,6,...,1.726000,33.390000,96890,0.016412,0.000000,0.000000,0.000000,110.939029,1281.198818,2074.900215
19,OQT,2008-07-03 09:53:00,15.56,86.18,0.00,288.71,8680,2008,184,9,...,1.726000,33.390000,96890,0.015723,0.000000,0.000000,0.000000,128.735011,1561.250558,1575.987671
20,OQT,2008-07-03 12:53:00,20.56,67.59,0.00,293.71,8695,2008,184,12,...,1.726000,33.390000,96890,0.016885,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,OQT,2008-07-03 15:53:00,27.78,40.84,3.45,300.93,8710,2008,184,15,...,1.770703,17.785427,96890,0.015729,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,OQT,2008-07-03 18:53:00,31.11,31.41,9.20,304.26,8725,2008,184,18,...,1.544223,13.070325,96890,0.014655,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,OQT,2008-07-03 21:53:00,31.11,30.39,8.05,304.26,8740,2008,184,21,...,1.492092,12.745372,96890,0.014179,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,OQT,2008-07-04 00:53:00,28.89,39.83,0.00,302.04,8755,2008,185,0,...,1.772652,17.104920,96890,0.016361,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,OQT,2008-07-04 03:53:00,23.89,61.66,0.00,297.04,8770,2008,185,3,...,1.730517,31.813309,96890,0.018863,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,OQT,2008-07-04 06:53:00,22.22,68.35,0.00,295.37,8785,2008,185,6,...,1.726000,33.390000,96890,0.018902,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,OQT,2008-07-04 09:53:00,21.67,75.57,0.00,294.82,8800,2008,185,9,...,1.726000,33.390000,96890,0.020209,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,OQT,2008-07-04 12:53:00,24.44,62.17,3.45,297.59,8815,2008,185,12,...,1.729532,32.156931,96890,0.019657,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,OQT,2008-07-04 15:53:00,28.33,52.93,8.05,301.48,8830,2008,185,15,...,1.747367,25.931301,96890,0.021048,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,OQT,2008-07-04 18:53:00,31.11,39.17,6.90,304.26,8845,2008,185,18,...,1.773926,16.660232,96890,0.018275,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
31,OQT,2008-07-04 21:53:00,31.67,36.42,4.60,304.82,8860,2008,185,21,...,1.779234,14.807366,96890,0.017541,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,OQT,2008-07-05 00:53:00,21.67,78.49,3.45,294.82,8875,2008,186,0,...,1.726000,33.390000,96890,0.020990,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
33,OQT,2008-07-05 03:53:00,21.11,87.26,0.00,294.26,8890,2008,186,3,...,1.726000,33.390000,96890,0.022549,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34,OQT,2008-07-05 06:53:00,20.56,89.98,0.00,293.71,8905,2008,186,6,...,1.726000,33.390000,96890,0.022478,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,OQT,2008-07-05 09:46:00,21.00,88.34,0.00,294.15,8920,2008,186,9,...,1.726000,33.390000,96890,0.022674,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,OQT,2008-07-05 12:07:00,21.00,88.34,0.00,294.15,8935,2008,186,12,...,1.726000,33.390000,96890,0.022674,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,OQT,2008-07-05 15:02:00,22.00,88.43,8.05,295.15,8950,2008,186,15,...,1.726000,33.390000,96890,0.024129,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,OQT,2008-07-05 18:53:00,28.33,54.63,4.60,301.48,8965,2008,186,18,...,1.744086,27.076709,96890,0.021724,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,OQT,2008-07-05 21:53:00,28.89,49.22,3.45,302.04,8980,2008,186,21,...,1.754528,23.431616,96890,0.020218,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
40,OQT,2008-07-06 00:53:00,23.89,73.59,0.00,297.04,8995,2008,187,0,...,1.726000,33.390000,96890,0.022513,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
41,OQT,2008-07-06 03:53:00,21.11,90.02,0.00,294.26,9010,2008,187,3,...,1.726000,33.390000,96890,0.023262,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
42,OQT,2008-07-06 06:53:00,21.11,87.26,0.00,294.26,9025,2008,187,6,...,1.726000,33.390000,96890,0.022549,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
43,OQT,2008-07-06 09:53:00,20.56,86.66,0.00,293.71,9040,2008,187,9,...,1.726000,33.390000,96890,0.021649,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44,OQT,2008-07-06 12:21:00,21.00,88.34,0.00,294.15,9055,2008,187,12,...,1.726000,33.390000,96890,0.022674,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
45,OQT,2008-07-06 15:53:00,26.11,64.54,6.90,299.26,9070,2008,187,15,...,1.726000,33.390000,96890,0.022536,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
46,OQT,2008-07-06 18:53:00,30.56,47.83,6.90,303.71,9085,2008,187,18,...,1.757211,22.495076,96890,0.021627,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
47,OQT,2008-07-06 21:53:00,31.11,40.44,4.60,304.26,9100,2008,187,21,...,1.771475,17.515919,96890,0.018868,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
48,OQT,2008-07-07 00:53:00,29.44,44.59,0.00,302.59,9115,2008,188,0,...,1.763465,20.312063,96890,0.018907,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
49,OQT,2008-07-07 03:53:00,23.33,68.57,0.00,296.48,9130,2008,188,3,...,1.726000,33.390000,96890,0.020282,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50,OQT,2008-07-07 06:53:00,20.56,80.86,0.00,293.71,9145,2008,188,6,...,1.726000,33.390000,96890,0.020200,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
51,OQT,2008-07-07 09:53:00,18.89,83.79,0.00,292.04,9160,2008,188,9,...,1.726000,33.390000,96890,0.018872,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
52,OQT,2008-07-07 12:53:00,23.33,73.49,5.75,296.48,9175,2008,188,12,...,1.726000,33.390000,96890,0.021737,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
53,OQT,2008-07-07 15:53:00,29.44,54.90,4.60,302.59,9190,2008,188,15,...,1.743565,27.258626,96890,0.023279,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
54,OQT,2008-07-07 18:53:00,31.11,42.02,6.90,304.26,9205,2008,188,18,...,1.768425,18.580475,96890,0.019605,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
55,OQT,2008-07-07 21:53:00,29.44,53.21,0.00,302.59,9220,2008,188,21,...,1.746827,26.119956,96890,0.022562,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [12]:
def write_txt(parameter_sens, geo_inputs, cycle_time, No_Cycle, Ads0_time, input_file = 'inputs.txt'):
    # x are the independent input, K_sb is the adjustable
    f = open(input_file, "w+")
    f.write("Ads0_time"+"\n")
    f.write(str(np.round(Ads0_time))+"\n"+"\n")     

    f.write("Ads_time"+"\n")
    f.write(str(np.round(cycle_time[0]))+"\n"+"\n")

    f.write("Des_time"+"\n")
    f.write(str(np.round(cycle_time[1]))+"\n"+"\n")

    f.write("No_Cycle"+"\n")
    f.write(str(No_Cycle)+"\n"+"\n")

    f.write("kf_1"+"\n")
    f.write(str(parameter_sens[0])+"\n"+"\n")

    f.write("kf_2"+"\n")
    f.write(str(parameter_sens[1])+"\n"+"\n")

    f.write("y_H2O_0"+"\n")
    f.write(str(geo_inputs[0])+"\n"+"\n")

    f.write("y_CO2_0"+"\n")
    f.write(str(geo_inputs[1])+"\n"+"\n")

    f.write("T_feed"+"\n")
    f.write(str(geo_inputs[2])+"\n"+"\n")

    f.write("P_atm"+"\n")
    f.write(str(geo_inputs[3])+"\n"+"\n")

    f.write("T_h2o"+"\n")
    f.write(str(geo_inputs[4])+"\n"+"\n")

    #print(cycle_time)
    f.close()
    
def sim_output(parameter_sens, geo_inputs, cycle_time):

    ads = np.round(cycle_time[0])
    Ads0 = ads*2
    vac1 = 5
    vac2 = 200
    vac3 = 100
    des = np.round(cycle_time[1])
    press1 = 20
    press2 = 200
    press3 = 5

    cycle = np.ceil(15000/(cycle_time[0]+cycle_time[1]))

    print(cycle_time, cycle)
    write_txt(parameter_sens, geo_inputs, cycle_time, No_Cycle = cycle, Ads0_time = Ads0, input_file = 'inputs.txt')


    gORUN_path = 'C:/Program Files/PSE/gPROMS-core_2021.2.0.55235/bin/goRUN.bat'
    gENCRYPT_name = 'H2O_export'
    activity = 'sim'
    process = 'H2O_export'
    password = 'H2O_export'

    call_gORUN(gORUN_path, gENCRYPT_name, activity, process, password, working_dir='./', time_out=24*3600,
                verbose=True)

    
    filename = 'C:/Users/xcai65/OneDrive - Georgia Institute of Technology/study/research/NETL/script/FACE/cost/output/H2O_export.gPLOT'
    output_results = gPLOT2df(filename)

    report_Des = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)-ads-press3-press2-press1
    report_Ads = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)
    report_Vac3 = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)-ads-press3-press2-press1-des-vac3

    try:
        #output_results['Time'] = np.round(output_results['Time'].values)
        prod_mass = output_results['Channel.PROD_MASS'][output_results['Time'] == report_Des].iloc[0] #mol/kg fiber/hr

        Out_CO2_des = output_results['Channel.OUT_CO2_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
        Out_N2_des = output_results['Channel.OUT_N2_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
        Out_H2O_des = output_results['Channel.OUT_H2O_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
        In_CO2_ads = output_results['Channel.IN_CO2_ads'][output_results['Time'] == report_Ads].iloc[0] #mol/channel

        Recovery = Out_CO2_des/In_CO2_ads
        Purity_CO2 = Out_CO2_des/(Out_CO2_des+Out_N2_des)
        #Purity_H2O = Out_H2O_des/(Out_CO2_des+Out_N2_des+Out_H2O_des)

        E_blower = output_results['Channel.E_blower_ash'][output_results['Time'] == report_Ads].iloc[0]/(Out_CO2_des*44.02*1e-6) # kWh/tCO2
        E_vac = output_results['Channel.E_vac'][output_results['Time'] == report_Des].iloc[0]/(Out_CO2_des*44.02*1e-6) # kWh/tCO2
        Q_sens_ads = -(output_results['Channel.H_ads_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                    output_results['Channel.H_ads_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
        Q_sens_CO2 = (output_results['Channel.H_CO2_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                    output_results['Channel.H_CO2_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
        Q_sens_H2O = (output_results['Channel.H_H2O_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                    output_results['Channel.H_H2O_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2    
        Q_ads_H2O = 50700*Out_H2O_des*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
        Q_ads_CO2 = (output_results['Channel.H_ads_CO2'][output_results['Time'] == report_Vac3].iloc[0]-\
                    output_results['Channel.H_ads_CO2'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2  

        E_blower = E_blower*27.78
        E_vac = E_vac*(Out_CO2_des+Out_N2_des)/(Out_CO2_des+Out_N2_des+Out_H2O_des)
    except:
        prod_mass = 0
        Recovery = 0
        Out_CO2_des = 0
        Out_N2_des = 0
        Out_H2O_des = 0
        #Purity_H2O = 0
        E_blower = 0
        E_vac = 0
        Q_sens_ads = 0
        Q_sens_CO2 = 0
        Q_sens_H2O = 0
        Q_ads_H2O = 0
        Q_ads_CO2 = 0


    
    return ([E_blower, E_vac, Q_sens_ads, Q_sens_CO2, Q_sens_H2O, Q_ads_CO2, Q_ads_H2O, prod_mass])

In [21]:
July = pd.read_csv('July_cost_20.csv', index_col=0)

In [22]:
July.columns

Index(['station', 'valid', 'tmpc', 'relh', 'sped', 'tmpK', 'index', 'YEAR',
       'DOY', 'HOUR', 'RING', 'CO2', 'WIND', 'WIND_DIR', 'SOLAR_ANG',
       'h2o_temperature', 'kf1, bar-1 s-1 (mol/kg)-1', 'kf2, bar2 s-1',
       'pressure', 'H2O_vol', 'E_cost', 'Ads_t, s', 'Des_t, s'],
      dtype='object')

In [23]:
output_E = np.zeros([July.shape[0], 8])

for i in range(July.shape[0]):
    sample = July.iloc[i, :]
    parameter_sens = [sample['kf1, bar-1 s-1 (mol/kg)-1']*1e-5, sample['kf2, bar2 s-1']*1e-10]
    geoinputs = [sample['H2O_vol'], sample['CO2']*1e-6, sample['tmpK'], sample['pressure'], sample['h2o_temperature']]
    cycle_time = [sample['Ads_t, s'], sample['Des_t, s']]

    output_E[i, :]= sim_output(parameter_sens, geoinputs, cycle_time)
    print(output_E[i, :],  i)

[1076.798622, 2387.666218] 5.0
gPROMS executed
[4.87326390e+02 1.20282180e+02 1.57280645e+03 6.53404047e+01
 3.53725580e+02 6.36766209e+02 8.96167883e+02 5.08168907e-01] 0
[1448.712926, 1346.068251] 6.0
gPROMS executed
[5.15098712e+02 1.16449237e+02 1.33251455e+03 6.48101895e+01
 7.39951512e+02 6.44267632e+02 1.79515916e+03 8.01932024e-01] 1
[1373.229512, 1804.181918] 5.0
gPROMS executed
[4.82534755e+02 1.15108738e+02 1.36190011e+03 6.41397668e+01
 1.07881142e+03 6.42897011e+02 2.60739045e+03 7.13873257e-01] 2
[1681.936031, 2461.069412] 4.0
gPROMS executed
[6.06526992e+02 1.14443057e+02 1.42458567e+03 6.36071907e+01
 1.37731863e+03 6.41807142e+02 3.32958556e+03 5.33551155e-01] 3
[1721.273399, 1488.616896] 5.0
gPROMS executed
[6.42601272e+02 1.16051363e+02 1.38167731e+03 6.50049349e+01
 8.86980648e+02 6.45890723e+02 2.13110198e+03 6.64749077e-01] 4
[1274.422577, 3567.291387] 4.0
gPROMS executed
[6.83210534e+02 1.21392833e+02 1.79701276e+03 6.53358272e+01
 3.34544979e+02 6.36025901e+02 8.59908784e+02 3.06879516e-01] 5
[1198.289006, 1204.322355] 7.0
gPROMS executed
[7.17598080e+02 1.22287337e+02 1.94672213e+03 6.53299739e+01
 2.94204930e+02 6.36048097e+02 7.72254380e+02 5.53715058e-01] 6
[991.4522584, 906.8764517] 8.0
gPROMS executed
[6.35446953e+02 1.23259121e+02 2.04919231e+03 6.48425903e+01
 2.04805737e+02 6.34009592e+02 5.70380735e+02 6.54618803e-01] 7
[1044.238298, 1544.971186] 6.0
gPROMS executed
[5.08632481e+02 1.20894032e+02 1.64467108e+03 6.56277703e+01
 3.26982328e+02 6.36448874e+02 8.33604263e+02 6.31645621e-01] 8
[1320.372423, 2487.796425] 4.0
gPROMS executed
[4.68944457e+02 1.16301828e+02 1.30612110e+03 6.53288472e+01
 7.70791919e+02 6.46182519e+02 1.85410636e+03 5.89006161e-01] 9
[1369.944458, 1645.240544] 5.0
gPROMS executed
[4.67352577e+02 1.15219637e+02 1.29626289e+03 6.47211911e+01
 9.85312533e+02 6.44948605e+02 2.36999578e+03 7.74890767e-01] 10
[1590.235261, 1481.355988] 5.0
gPROMS executed
[5.66566095e+02 1.14639805e+02 1.37955089e+03 6.41008951e+01
 1.25398259e+03 6.43471811e+02 3.01838407e+03 7.28372852e-01] 11
[1743.75, 1537.5] 5.0
gPROMS executed
[6.46562256e+02 1.15601484e+02 1.36273336e+03 6.52248701e+01
 9.87445640e+02 6.47288794e+02 2.35701580e+03 6.54836214e-01] 12
[1203.458338, 2112.209202] 5.0
gPROMS executed
[6.47130257e+02 1.20363983e+02 1.78927661e+03 6.57665783e+01
 4.89933027e+02 6.40451530e+02 1.21042841e+03 4.46779631e-01] 13
[962.731139, 992.5909147] 8.0
gPROMS executed
[6.88296720e+02 1.23505046e+02 2.26784593e+03 6.46458705e+01
 2.61772572e+02 6.34965377e+02 7.16099206e+02 5.69871009e-01] 14
[942.7084256, 1326.825073] 7.0
gPROMS executed
[6.10880477e+02 1.22860292e+02 2.04540962e+03 6.54897648e+01
 2.73399949e+02 6.36329130e+02 7.26415334e+02 5.41745421e-01] 15
[994.0837336, 1039.246678] 8.0
gPROMS executed
[4.96630405e+02 1.20467542e+02 1.64654041e+03 6.61421367e+01
 4.03683492e+02 6.39680684e+02 1.00347578e+03 7.84389882e-01] 16
[1324.508966, 2511.922288] 4.0
gPROMS executed
[4.82321592e+02 1.16845352e+02 1.30181429e+03 6.58684299e+01
 6.88940255e+02 6.47903553e+02 1.65279267e+03 5.70455988e-01] 17
[1281.198818, 2074.900215] 5.0
gPROMS executed
[4.45519923e+02 1.15140258e+02 1.29574760e+03 6.51510043e+01
 1.03895167e+03 6.46668227e+02 2.48054914e+03 6.82876623e-01] 18
[1561.250558, 1575.987671] 5.0
gPROMS executed
[5.54589261e+02 1.14567826e+02 1.34949531e+03 6.46168971e+01
 1.26591751e+03 6.45454318e+02 3.02632650e+03 7.15155209e-01] 19
[nan, nan] nan
gPROMS executed
[0. 0. 0. 0. 0. 0. 0. 0.] 20
[nan, nan] nan
gPROMS executed
[0. 0. 0. 0. 0. 0. 0. 0.] 21
[nan, nan] nan
gPROMS executed
[0. 0. 0. 0. 0. 0. 0. 0.] 22
[nan, nan] nan
gPROMS executed
[0. 0. 0. 0. 0. 0. 0. 0.] 23
[nan, nan] nan
gPROMS executed
[0. 0. 0. 0. 0. 0. 0. 0.] 24
[nan, nan] nan
gPROMS executed
[0. 0. 0. 0. 0. 0. 0. 0.] 25
[nan, nan] nan
gPROMS executed

KeyboardInterrupt:

In [ ]:
df_output_E = pd.DataFrame(output_E, columns = ['E_blower', 'E_vac', 'Q_sens_ads', 'Q_sens_CO2', 'Q_sens_H2O', 'Q_ads_CO2', 'Q_ads_H2O', 'Optimized Prod'])
df_output_E['Cost_E, $/tCO2'] = df_output_E.iloc[:, :2].sum(axis = 1)*0.05
df_output_E['Cost_H, $/tCO2'] = df_output_E.iloc[:, 2:7].sum(axis = 1)*0.015

df_final = pd.concat([July, df_output_E], axis = 1)
df_final.to_csv('July_cost_20.csv')